# Generated by Django 3.0.3 on 2020-11-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.IntegerField()),
                ('class_name', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='planet_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=6)),
                ('psname', models.CharField(max_length=6)),
                ('pvalue', models.IntegerField()),
                ('pspeed_max', models.IntegerField()),
                ('pflight_max', models.IntegerField()),
                ('pcombat_radius', models.IntegerField()),
                ('pload_max', models.IntegerField()),
                ('plongitude', models.FloatField()),
                ('platitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='radar_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsid', models.CharField(max_length=7)),
                ('rsname', models.CharField(max_length=7)),
                ('rtype', models.CharField(max_length=7)),
                ('rop_band', models.IntegerField()),
                ('rpulse_width', models.IntegerField()),
                ('rantenna_gain', models.IntegerField()),
                ('rpulse_freq', models.IntegerField()),
                ('rtrans_power', models.IntegerField()),
                ('rradius_max', models.IntegerField()),
                ('rdist_max', models.IntegerField()),
                ('rdist_min', models.IntegerField()),
                ('rpos_accuracy', models.IntegerField()),
                ('ranti_interference', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=10)),
                ('classes', models.IntegerField()),
                ('model', models.IntegerField()),
            ],
        ),
    ]
