# Generated by Django 3.0.3 on 2020-11-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arm_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asname', models.IntegerField()),
                ('atype', models.CharField(max_length=7)),
                ('aspeed', models.IntegerField()),
                ('akill_radius', models.IntegerField()),
                ('ahit_rate', models.FloatField()),
                ('aguide_accuracy', models.IntegerField()),
                ('ahit_accuracy', models.IntegerField()),
                ('aattack_distmax', models.IntegerField()),
                ('aattack_distmin', models.IntegerField()),
                ('afight_heightmax', models.IntegerField()),
                ('afight_heightmin', models.IntegerField()),
                ('areliability', models.FloatField()),
                ('aanti_interference', models.FloatField()),
                ('astealth', models.FloatField()),
                ('areaction_time', models.FloatField()),
                ('apayload', models.FloatField()),
                ('aguide_type', models.IntegerField()),
                ('avalue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='compute_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csname', models.IntegerField()),
                ('ctype', models.CharField(max_length=7)),
                ('caccuracy', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='radar_info',
            name='rsid',
        ),
        migrations.AlterField(
            model_name='radar_info',
            name='rsname',
            field=models.IntegerField(),
        ),
    ]
