# Generated by Django 3.0.3 on 2020-11-11 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Only_Id', models.CharField(max_length=240, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('port', models.CharField(max_length=100, null=True)),
                ('cpu_cores', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('mountPoint', models.CharField(max_length=254, null=True)),
                ('volume_name', models.CharField(max_length=254, null=True)),
                ('state', models.IntegerField(default=0, help_text='0:running;1:stop;')),
                ('is_del', models.BooleanField(default=False, help_text='true:not deleted; false:deleted')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='docker_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=50, null=True)),
                ('mountPoint', models.CharField(max_length=100, null=True)),
                ('underSystem', models.CharField(max_length=50, null=True)),
                ('port', models.CharField(max_length=100, null=True)),
                ('command', models.CharField(max_length=100, null=True)),
                ('repository', models.CharField(max_length=50, null=True)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('deploy_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='docker_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('ssh_port', models.IntegerField()),
                ('user', models.CharField(max_length=20, null=True)),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('deploy_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('home_dir', models.CharField(max_length=30, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='new_docker_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_ip', models.GenericIPAddressField()),
                ('cpu_cores', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('apply_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain_node', models.CharField(max_length=20, null=True)),
                ('state', models.IntegerField(default=0, help_text='0:no deal;1:agree;2:refuse;')),
                ('img_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='container.docker_img')),
            ],
        ),
    ]
