# Generated by Django 3.0.3 on 2020-11-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_auto_20201111_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='memory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='new_docker_apply',
            name='memory',
            field=models.FloatField(),
        ),
    ]
