# Generated by Django 3.0.3 on 2020-11-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_auto_20201113_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='docker_node_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=39)),
                ('ssh_port', models.IntegerField()),
                ('user', models.CharField(max_length=20, null=True)),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('home_dir', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
