# Generated by Django 3.0.3 on 2020-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_docker_node_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_docker_apply',
            name='classes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='new_docker_apply',
            name='model',
            field=models.IntegerField(null=True),
        ),
    ]
