# Generated by Django 3.0.3 on 2020-11-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_auto_20201127_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker_node',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
