# Generated by Django 3.0.3 on 2020-11-29 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vm', '0004_vm_available'),
        ('container', '0006_docker_node_is_del'),
    ]

    operations = [
        migrations.CreateModel(
            name='container_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Only_Id', models.CharField(max_length=240, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('port', models.CharField(max_length=100, null=True)),
                ('cpu_cores', models.IntegerField()),
                ('memory', models.FloatField()),
                ('mountPoint', models.CharField(max_length=254, null=True)),
                ('volume_name', models.CharField(max_length=254, null=True)),
                ('state', models.IntegerField(default=0, help_text='0:running;1:stop;')),
                ('is_del', models.BooleanField(default=False, help_text='true:not deleted; false:deleted')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='container.docker_img')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='container.docker_node')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
