# Generated by Django 3.0.3 on 2021-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0007_container_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docker_node',
            name='is_del',
        ),
        migrations.RemoveField(
            model_name='new_docker_apply',
            name='regionID',
        ),
        migrations.AddField(
            model_name='docker_node',
            name='is_zabbix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new_docker_apply',
            name='region_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
