# Generated by Django 3.0.3 on 2020-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qappx',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpu', models.IntegerField(null=True)),
                ('mem', models.IntegerField(null=True)),
                ('a', models.IntegerField(null=True)),
                ('Q', models.FloatField(null=True)),
            ],
        ),
    ]
