# Generated by Django 3.0.3 on 2020-11-11 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('gw_ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=20, null=True)),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('state', models.BooleanField(default=True)),
                ('vt_type', models.CharField(default='KVM', max_length=20)),
                ('deploy_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sync_time', models.DateTimeField(default=None, null=True)),
                ('home_dir', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vm_os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_version', models.CharField(max_length=30)),
                ('iso_path', models.CharField(max_length=100, null=True)),
                ('template_path', models.CharField(max_length=100, null=True)),
                ('default_user', models.CharField(default=None, max_length=15, null=True)),
                ('default_pwd', models.CharField(default=None, max_length=30, null=True)),
                ('default_port', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='workstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('ssh_port', models.IntegerField()),
                ('user', models.CharField(max_length=20, null=True)),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('deploy_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('home_dir', models.CharField(max_length=30, null=True)),
                ('state', models.BooleanField(default=True)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.domain')),
            ],
        ),
        migrations.CreateModel(
            name='vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('vCPUs', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('diskSize', models.IntegerField(default=0)),
                ('diskAllocation', models.IntegerField(null=True)),
                ('diskType', models.CharField(default='qcow2', max_length=20)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('gateway_ip', models.GenericIPAddressField()),
                ('os_version', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('apply_time', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('power_state', models.CharField(default='running', max_length=20, null=True)),
                ('state', models.BooleanField(default=True, help_text='true:normal; false:not using or will be recycle')),
                ('is_del', models.BooleanField(default=False, help_text='true:not deleted; false:deleted')),
                ('noVNC_port', models.IntegerField(null=True)),
                ('isPersistent', models.BooleanField(default=True, help_text='true:persistent;false:transitent')),
                ('conn_port', models.IntegerField(default=None, null=True)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.workstation')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.vm_os')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshotName', models.CharField(max_length=50, null=True)),
                ('snapshotId', models.CharField(max_length=50, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_exist', models.BooleanField(default=True, help_text='true:not deleted; false:deleted')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vmname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.vm')),
            ],
        ),
        migrations.CreateModel(
            name='port_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmPort', models.IntegerField()),
                ('mapPort', models.IntegerField(default=None, null=True)),
                ('apply_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('operate_time', models.DateTimeField(default=None, null=True)),
                ('state', models.IntegerField(default=0, help_text='0:no deal;1:agree;2:refuse;3:delete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.vm')),
            ],
        ),
        migrations.CreateModel(
            name='new_vm_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_ip', models.GenericIPAddressField()),
                ('cpu_cores', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('apply_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.IntegerField(default=0, help_text='0:no deal;1:agree;2:refuse;')),
                ('isPersistent', models.BooleanField(default=True, help_text='true:persistent;false:transitent')),
                ('installway', models.CharField(default='clone', max_length=10)),
                ('os_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.vm_os')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deploy_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vCPUs', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('diskSize', models.IntegerField(default=0)),
                ('apply_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('operate_time', models.DateTimeField(default=None, null=True)),
                ('state', models.IntegerField(default=0, help_text='0:no deal;1:agree;2:refuse;')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.vm')),
            ],
        ),
    ]
