# Generated by Django 3.0.3 on 2020-11-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0002_auto_20201127_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
