# Generated by Django 3.0.3 on 2020-11-29 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vm', '0003_workstation_is_del'),
    ]

    operations = [
        migrations.CreateModel(
            name='vm_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('vCPUs', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('diskSize', models.IntegerField(default=0)),
                ('diskAllocation', models.IntegerField(null=True)),
                ('diskType', models.CharField(default='qcow2', max_length=20)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('gateway_ip', models.GenericIPAddressField()),
                ('os_version', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('apply_time', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('power_state', models.CharField(default='running', max_length=20, null=True)),
                ('state', models.BooleanField(default=True, help_text='true:normal; false:not using or will be recycle')),
                ('is_del', models.BooleanField(default=False, help_text='true:not deleted; false:deleted')),
                ('noVNC_port', models.IntegerField(null=True)),
                ('isPersistent', models.BooleanField(default=True, help_text='true:persistent;false:transitent')),
                ('conn_port', models.IntegerField(default=None, null=True)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.workstation')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.vm_os')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
