# Generated by Django 3.0.3 on 2021-05-11 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0005_cascade_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstation',
            name='is_del',
        ),
        migrations.AddField(
            model_name='workstation',
            name='is_zabbix',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='apply_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('ssh_port', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('deploy_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('home_dir', models.CharField(max_length=30, null=True)),
                ('state', models.IntegerField(default=0, help_text='0:no deal;1:agree')),
                ('belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vm.domain')),
            ],
        ),
    ]
