# Generated by Django 3.0.3 on 2021-05-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0006_auto_20210511_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy_apply',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.vm'),
        ),
        migrations.AlterField(
            model_name='port_apply',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.vm'),
        ),
    ]
