# Generated by Django 3.0.3 on 2021-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0007_auto_20210513_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='cascade_list',
            name='is_ping',
            field=models.BooleanField(default=False, help_text='false: no ping, true: ping', null=True),
        ),
    ]
